#!/usr/bin/perl

use warnings;
use strict;
use JSON;
use XML::RSSLite;

my $url = 'https://status.dev.azure.com/_rss';
my %status = (
	name	=> 'Azure DevOps',
	url	=> 'https://status.dev.azure.com/',
	feed    => $url,
	results => []
);
my $feed=`curl -skL "$url"`;
my $today=`date -R | awk '{print \$1,\$2,\$3,\$4}'`;
chomp $today;

if($feed !~ /<title>Azure DevOps.*<\/title>/) {
	print '{ "name": "Azure", "fetch": "unknown", "details": "Feed fetch failed!", "results": []}';
	exit;
} else {
	# Try to parse RSS
	my %result;
	parseRSS(\%result, \$feed);
	foreach my $item (@{$result{'item'}}) {
		if($item->{'pubDate'} =~ /^$today/) {
			push(@{$status{results}}, {
				time        => $item->{pubDate},
				title       => $item->{title},
				description => $item->{description}
			})
		}
	}
}
print to_json(\%status);
