#!/usr/bin/perl

use warnings;
use strict;
use XML::Feed;
use JSON;

my $today=`date -I`;
chomp $today;
my $url = "https://status.cloud.google.com/feed.atom";
my $data = `curl -sk "$url"`;
my %status = (
	name => 'Google Cloud',
	url  => 'https://status.cloud.google.com/',
	feed => $url,
	results => []
);
my $feed = XML::Feed->parse(\$data);

unless(defined($feed) && defined($feed->entries)) {
	print '{ "fetch": "unknown", "details": "Fetch fetch failed!"}';
	exit;
}

foreach ($feed->entries) {
	next unless($_->updated =~ /^$today/);
	push(@{$status{'results'}}, {
		time		=> $_->updated,
		title		=> $_->title,
		description	=> $_->content->body
	});
}

print to_json(\%status);
